# Generated by Django 3.0.2 on 2020-01-17 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Body',
        ),
    ]
