# Generated by Django 3.0.2 on 2020-01-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_delete_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='key_words',
            new_name='keywords',
        ),
    ]
