# Generated by Django 3.0.2 on 2020-01-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_auto_20200119_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
