# Generated by Django 3.0.2 on 2020-01-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_auto_20200127_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, to='recipe_app.Favorite', verbose_name='Favorite'),
        ),
    ]
