# Generated by Django 3.0.2 on 2020-01-28 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_app', '0009_auto_20200127_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Favorite'),
        ),
    ]
