# Generated by Django 3.0.2 on 2020-01-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0010_auto_20200127_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='favorite_recipes',
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_recipes',
            field=models.ManyToManyField(to='recipe_app.Recipe'),
        ),
    ]
