# Generated by Django 3.0.2 on 2020-01-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0014_auto_20200129_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
