# Generated by Django 3.0.2 on 2020-02-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0019_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.CharField(max_length=500),
        ),
    ]
